trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals wsl_agent

steps:
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Download'
    connection: 'mvc_azure'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "maven_azure-libs-snapshot-local/maven_mvc.war/target/maven_mvc-0.0.1-SNAPSHOT.war",
            "target": "$(System.ArtifactorysDirectory)/drop/",
            "flat": "true"
          }
        ]
      }
    failNoOp: true

- task: Docker@2
  inputs:
    containerRegistry: 'azure_maven'
    repository: 'piyush1232/maven_azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(System.ArtifactorysDirectory)'
    tags: 'latest'

- task: Bash@3
  displayName: "Deploy Docker Container"
  inputs:
    targetType: 'inline'
    script: |
      docker pull piyush1232/maven_azure:latest
      docker rm -f maven_app || true
      docker run -d --restart=always -p 5050:8080 --name maven_app piyush1232/maven_azure:latest
