
name: Advanced CI Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main
    - develop

jobs:
  build_and_test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      if: hashFiles('pom.xml') != ''
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Restore dependencies (Java)
      if: hashFiles('pom.xml') != ''
      run: mvn dependency:resolve

    - name: Build the application (Java)
      if: hashFiles('pom.xml') != ''
      run: mvn clean package 

    - name: Run JUnit Tests (Java)
      if: hashFiles('pom.xml') != ''
      run: mvn test
      continue-on-error: true

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=Piyush-ngro_actions_task1
          -Dsonar.organization=Piyush-ngro
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.verbose=true
          -Dsonar.java.binaries=target/classes
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml




 
 


   
